#!/bin/bash

MY_IP=`/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1`
DEV_DOMAIN="${MY_IP}.xip.io"
OUTFILE=./env

echo "DEV_DOMAIN=${DEV_DOMAIN}" > ${OUTFILE}
echo "GOVUK_APP_DOMAIN=${DEV_DOMAIN}" >> ${OUTFILE}
echo "GDS_SSO_STRATEGY=real" >> ${OUTFILE}
echo "STATIC_DEV=http://static.${DEV_DOMAIN}" >> ${OUTFILE}
echo "GOVUK_ASSET_ROOT=static.${DEV_DOMAIN}" >> ${OUTFILE}
echo "PANOPTICON_USER='api'" >> ${OUTFILE}
echo "PANOPTICON_PASSWORD='mysuperawesomepassword'" >> ${OUTFILE}

cat ./mandrillcreds >> ${OUTFILE}
cat ./oauthkeys >> ${OUTFILE}

