#!/bin/bash

if [[ `uname` == 'Darwin' ]]; then
  DOMAIN="dev"
else
  MY_IP=`/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1`
  DOMAIN="${MY_IP}.xip.io"
fi

OUTFILE=./env

echo "GOVUK_APP_DOMAIN=${DOMAIN}" > ${OUTFILE}
echo "DEV_DOMAIN=${DOMAIN}" >> ${OUTFILE}
echo "GDS_SSO_STRATEGY=real" >> ${OUTFILE}
echo "STATIC_DEV=http://static.${DOMAIN}" >> ${OUTFILE}
echo "GOVUK_ASSET_ROOT=static.${DOMAIN}" >> ${OUTFILE}
echo "PANOPTICON_USER='api'" >> ${OUTFILE}
echo "PANOPTICON_PASSWORD='mysuperawesomepassword'" >> ${OUTFILE}
echo "CONTENTAPI_DEFAULT_ROLE=odi" >> ${OUTFILE}
echo "RUMMAGER_HOST=http://search.dev" >> ${OUTFILE}

cat ./rackspacecreds >> ${OUTFILE}
cat ./mandrillcreds >> ${OUTFILE}
cat ./oauthcreds >> ${OUTFILE}
cat ./juviacreds >> ${OUTFILE}
